name: Build and Deploy to Prod

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.x.x'

      - name: Debug
        run: |
          echo "Hello, world!"

      - name: Output the FullSemVer variable
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.2.1

      - name: Create and push tag
        run: |
          echo "SemVer: ${{ steps.version_step.outputs.semVer }}"
          echo "MajorMinorPatch: ${{ steps.version_step.outputs.majorMinorPatch }}"
          git tag "v${{ steps.version_step.outputs.majorMinorPatch }}"
          git push origin "v${{ steps.version_step.outputs.majorMinorPatch }}"
