name: Build and Deploy to Stage

on:
  push:
    branches:
      - release/*

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.x.x'

      - name: Debug
        run: |
          echo "Hello, world!"

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.2.1
