name: Build and Deploy to Sandbox

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Hello, world!"
