name: Build for Develop

on:
  push:
    branches:
      - develop

concurrency:
  group: sandbox-build
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Hello, world!"
