name: Check PR

on:
  push:
    branches:
      - feature/*
      - hotfix/*

jobs:
  build:
    name: "Check PR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          sleep 300
          echo "Hello, world!"
