name: Check PR

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: "Check PR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.x.x'

      - name: Debug
        run: |
          sleep 20
          echo "Hello, world!"

      - name: Output the FullSemVer variable
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: true
          configFilePath: gitversion.yml
          arguments: '/showvariable FullSemVer'
